### ISSUE TITLE
Infinite recursion

### ISSUE THREAD

**Issue by n8ores** [vlasky/mysql-live-select#6]
LiveMySql.js Line 69 has the following line: 

`self.zongji.child.on('child', child => self.zongji.emit('child', child, reason));`

This is causing an infinite recursion. An event handler is attached to the child, and inside that event handler, we are emitting another event on the child.

Changing the code to once rectifies this issue:

`self.zongji.child.once('child', child => self.zongji.emit('child', child, reason));`

**Comment by vlasky** [comment]
I recently released version 1.2.26, in which the binlog resume code has been rewritten to be simpler and more robust. It no longer generates or listens for the 'child' event, so this issue can no longer occur.
